# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

footprintingAnalysis <- function(center_sizes, center_position, start, end, flank_windows, wide_flank, bardata) {
    .Call('_tracebind_footprintingAnalysis', PACKAGE = 'tracebind', center_sizes, center_position, start, end, flank_windows, wide_flank, bardata)
}

